import { FlatCompat } from '@eslint/eslintrc'

const compat = new FlatCompat({
  baseDirectory: import.meta.dirname,
})

const eslintConfig = [
  ...compat.extends('next/core-web-vitals', 'next/typescript'),
  {
    // legacy-vite/ holds pre-migration reference files, ported + removed by end of Phase 5.
    // next-env.d.ts is auto-generated by Next.js and requires its triple-slash reference.
    ignores: ['.next/**', 'node_modules/**', 'dist/**', 'legacy-vite/**', 'next-env.d.ts'],
  },
]

export default eslintConfig
